INSERT INTO USER_DETAILS(AGE,ID,ADDRESS,NAME) VALUES (24,101,'bogura', 'ayon');
INSERT INTO USER_DETAILS(AGE,ID,ADDRESS,NAME) VALUES (29,202,'dhaka', 'zenin');
INSERT INTO USER_DETAILS(AGE,ID,ADDRESS,NAME) VALUES (24,303,'usa', 'nilu');
